src/apis/character.ts
src/apis/encryption.ts
src/apis/sign.ts
src/apis/user.ts

> 작업 내용에 대한 설명
* 모든 API 요청에 대한 request, response 타입 및 요청 정의
> PR 전 체크해주세요.

[Feat] 모든 api fetch 코드 구현

---

package.json
pnpm-lock.yaml
src/App.tsx
src/components/Layout.tsx
src/components/MobileBlockScreen.tsx
src/components/ui/sonner.tsx
src/lib/router.tsx
src/pages/UserPage.tsx

> 작업 내용에 대한 설명
* 유저페이지 구현
* 모바일 화면 규격에서 접근할 수 없도록 블락 
```ts
import { toast } from 'sonner';
toast.success('이미지 태그가 복사되었습니다.');
```
sonner를 사용할거라면 다음과 같이 사용하시면 됩니다. 
> PR 전 체크해주세요.

[Feat] 유저페이지 구현

---

src/apis/character.ts
src/apis/encryption.ts
src/apis/sign.ts
src/apis/user.ts

> closes #1
> 작업 내용에 대한 설명
> 작업 결과물
> PR 전 체크해주세요.

feat: 모든 api fetch 코드 구현

---

package.json
pnpm-lock.yaml
src/components/Layout.tsx
src/components/ui/dialog.tsx
src/lib/router.tsx
src/pages/NotFoundPage.tsx
src/pages/SalePage.tsx

> 작업 내용에 대한 설명
1. 판매 페이지 구현
2. 각 상품 선택 - 초기화 / 판매 로직 구현
> 작업 결과물
> PR 전 체크해주세요.

[Feat] 판매 페이지 구현

---

package.json
pnpm-lock.yaml
src/App.tsx
src/apis/user.ts
src/components/ErrorBoundary.tsx
src/components/Layout.tsx
src/components/RetroLoading.tsx
src/lib/queryClient.ts
src/lib/router.tsx
src/pages/NotFoundPage.tsx
src/pages/UserPage.tsx
src/pages/index.tsx
tailwind.config.js

> 작업 내용에 대한 설명
* 유저 페이지 데이터 페칭
* 에러바운더리
* Suspense
> 작업 결과물
추후에 추가하도록 하겠습니다. 
> PR 전 체크해주세요.

[Feat] 유저 페이지 데이터 페칭

---

src/components/Header.tsx
src/components/Layout.tsx
src/components/ui/label.tsx
src/index.css
src/pages/gacha/index.tsx

> 작업 내용에 대한 설명
> 작업 결과물
> PR 전 체크해주세요.

[Design] 이미지 상단부터 렌더링 되게 수정

---

src/components/gacha/GachaConfirmDialog.tsx
src/components/gacha/GachaDropRateInfo.tsx
src/components/gacha/GachaResultModal.tsx
src/components/gacha/PointDisplay.tsx
src/index.css
src/pages/gacha/index.tsx

> closes #1
> 작업 내용에 대한 설명
- 폰트 `갈무리11`체로 변경
- 폰트 크기 css에서 조정
- 바뀐 크기에 맞게 가챠 페이지 ui 살짝 수정
> 작업 결과물
> PR 전 체크해주세요.

design: 폰트 적용, 가챠페이지 ui 수정

---

src/pages/profile/AvatarCollection.tsx
src/pages/profile/MyAvatar.tsx
src/pages/profile/PlayerInfo.tsx
src/pages/profile/index.tsx

[Design] : 프로필페이지 수정

---

src/apis/encryption.ts
src/apis/sign.ts
src/components/Layout.tsx
src/pages/login/index.tsx
src/pages/signup/index.tsx

[Feat] : auth API 연결

---

src/apis/avatar.ts
src/apis/user.ts

> closes #1
> 작업 내용에 대한 설명
> 작업 결과물
> PR 전 체크해주세요.

[FIX] header에 토큰 담기

---

src/components/ErrorBoundary.tsx
src/components/Root.tsx
src/components/gacha/GachaDropRateInfo.tsx
src/lib/router.tsx
src/pages/gacha/index.tsx

> 작업 내용에 대한 설명
* 가챠페이지에서 새로고침했을 때 렌더링 이슈가 있던것을 수정합니다. 
> PR 전 체크해주세요.

[FIX] redner error

---

src/components/Header.tsx
src/pages/service/components/CatGallery.tsx
src/pages/service/components/Footer.tsx
src/pages/service/components/ServiceIntro.tsx

[Design] 메인화면 새로운 디자인

---

src/apis/user.ts
src/components/Layout.tsx
src/pages/profile/AvatarCollection.tsx
src/pages/profile/MyAvatar.tsx
src/pages/profile/PlayerInfo.tsx
src/pages/profile/index.tsx

> 작업 결과물
* `mutate` 는 promise를 반환하는 함수를 사용해야합니다. 
> PR 전 체크해주세요.

[Design] 프로필페이지 UI 수정

---

src/apis/user.ts
src/components/Header.tsx
src/components/ui/sonner.tsx
src/lib/router.tsx
src/pages/gacha/index.tsx
src/pages/profile/PlayerInfo.tsx
src/pages/sale/index.tsx
src/pages/service/components/CatGallery.tsx

> 작업 내용에 대한 설명
* 캐릭터 판매 로직을 변경합니다
* 헤더로 판매 탭을 이동합니다
* 추후에 경매장 시스템이 도입될것을 고려해 Auction 으로 키워드를 선택했습니다ㅣ 
> PR 전 체크해주세요.

[Feat] 캐릭터 판매 로직

---

index.html
src/pages/gacha/components/GachaResultModal.tsx
src/pages/service/components/CatGallery.tsx

> closes #1
> 작업 내용에 대한 설명
> 작업 결과물
> PR 전 체크해주세요.

[Chore] 메타태그 업데이트

---

src/pages/gacha/components/GachaResultModal.tsx
src/pages/gacha/components/SummaryItem.tsx
src/pages/gacha/components/SummaryView.tsx
src/pages/gacha/constants/catMappings.ts
src/pages/gacha/hooks/usePreloader.tsx
src/pages/gacha/index.tsx
src/pages/service/components/CatGallery.tsx

[Refactor] 이미지 프리업로더

---

src/apis/user.ts
src/components/Layout.tsx
src/components/ui/card.tsx
src/index.css
src/pages/gacha/components/SummaryView.tsx
src/pages/gacha/index.tsx
src/pages/login/index.tsx
src/pages/profile/AvatarCollection.tsx
src/pages/profile/MyAvatar.tsx
src/pages/profile/PlayerInfo.tsx
src/pages/sale/index.tsx
src/pages/service/components/CatGallery.tsx
src/pages/service/components/Footer.tsx
src/pages/service/components/ServiceIntro.tsx
src/pages/signup/index.tsx

> closes #1
> 작업 내용에 대한 설명
> 작업 결과물
> PR 전 체크해주세요.

[Design] 레이아웃 구조 변경

---

src/components/Header.tsx
src/index.css

> closes #45 
> 작업 내용에 대한 설명
1. 드롭박스 ui 수정
2. 카테고리 한국어로 변경
* 문제점 
1. 드롭박스가 열리면 헤더가 가로로 길어진다...
2. 상위css에 보라색 글씨 효과가 있는 것 같은데... 내정보 글씨를 하얗게 바꾸면서 호버효과를 로그아웃과 동일하게 주려고 했지만 구현 미
> 작업 결과물
> PR 전 체크해주세요.

Feat/header dropbox/heee1

---

src/apis/user.ts
src/pages/sale/index.tsx
src/pages/service/components/Footer.tsx

[Feat] sale API 연결

---

src/pages/gacha/components/Confetti.ts
src/pages/gacha/components/GachaDropRateInfo.tsx
src/pages/gacha/components/PointDisplay.tsx
src/pages/gacha/index.tsx

> closes #2
> 작업 내용에 대한 설명
1. 폰트 크기 너무 큰 것 같아서 좀 작게 조정
2. 컨페티 좀 더 멀리 퍼지게
> 작업 결과물
> PR 전 체크해주세요.

[Design] 컨페티 더 팡~ 터지게

---

src/apis/user.ts
src/pages/profile/MyAvatar.tsx

[Feat] 이미지 합성

---

index.html
src/components/Header.tsx
src/components/Layout.tsx
src/components/RetroLoading.tsx
src/components/ui/dialog.tsx
src/components/ui/dropdown-menu.tsx
src/pages/gacha/components/GachaDropRateInfo.tsx
src/pages/profile/AvatarCollection.tsx
src/pages/profile/MyAvatar.tsx
src/pages/profile/PlayerInfo.tsx
src/pages/sale/index.tsx
src/pages/service/components/CatGallery.tsx
src/pages/service/components/ServiceIntro.tsx
src/pages/signup/index.tsx

[Refactor] 플로우체크, HotFix

---

src/components/Header.tsx
src/lib/router.tsx
src/pages/contest/index.tsx

> 작업 내용에 대한 설명
- 헤더에 라우팅 추가
- 공모전 준비중 페이지 추가
> 작업 결과물
> PR 전 체크해주세요.

[Feat] 공모전 준비 페이지 추가

---

src/apis/user.ts
src/pages/gacha/index.tsx
src/pages/sale/index.tsx
src/pages/service/components/ServiceIntro.tsx
src/pages/service/index.tsx

[Hotfix] 최종 배포전 수정
